language: go

go:
- "1.x"
- tip

env:
  global:
    secure: uK1KK2M1+9MCfV5KUNK0ErMM7FemG5CrOId3iCic9MQQDnJNfd8JCte/zfD3EtMoRbUDJ8+ghAhuC0z52IXu6hQFeja4kPkKQevOCI38QCmaGrMog+T8L9lR+agaJvu3BYAjupCPJxrKQ5d27MGOdgZNr3gGHGggTzNF7lkxeBSE2/zSZxeA56CzXEtMMQg+XFoe9FfVFyNirHhRhIlAxSgnvjL/+c04a0GStTsSPKE1FxhrVf/SBewcRr6vJbngE+CuXUwcA9aEI+GfAomJvzoGBDIeK7cVN8La67wXjJQie3zvR+U92Yv3+Gr/BIcsolriSrAiMoRF+MnFkTXJoCotK/tdMfdDh7kD2bsy3EACb/1nkROZhXrOMqWEG4bJrld0MKMGIEijxWAo38BlwllCk7eNOWzT2N55rvjKEtvH7dQbSX3mAtxUqFtxzOA/ZHMEh5cbXmSn/hVUTAhashGEUmD3Ff5bQ/0MmVCU44zm9z68m5Zw5geZNax7MaT77f065zxLzH6SiI+kwb/ocmb9rjHmNV6IYuYJKcRE1EU7rAJqmazicEri/+BsFO6Q3a0M54fSm5yS0DWPTbYuyuvWkVqL/0ZACFGTO+tB4d7th+cfMd+j+vdnqfMMTNxxbMWyjHHZtNGkwRQm5WUk4f6LUIRpcM+XZFd82utEg/4=
